package hibernate;
// Generated 2016-5-14 18:48:55 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Dormitory generated by hbm2java
 */
public class Dormitory implements java.io.Serializable {

	private String droomNr;
	private int capacity;
	private Set<Students> studentses = new HashSet<Students>(0);

	public Dormitory() {
	}

	public Dormitory(String droomNr, int capacity) {
		this.droomNr = droomNr;
		this.capacity = capacity;
	}

	public Dormitory(String droomNr, int capacity, Set<Students> studentses) {
		this.droomNr = droomNr;
		this.capacity = capacity;
		this.studentses = studentses;
	}

	public String getDroomNr() {
		return this.droomNr;
	}

	public void setDroomNr(String droomNr) {
		this.droomNr = droomNr;
	}

	public int getCapacity() {
		return this.capacity;
	}

	public void setCapacity(int capacity) {
		this.capacity = capacity;
	}

	public Set<Students> getStudentses() {
		return this.studentses;
	}

	public void setStudentses(Set<Students> studentses) {
		this.studentses = studentses;
	}

}
