package hibernate;
// Generated 2016-5-14 18:48:55 by Hibernate Tools 4.3.1.Final

/**
 * Students generated by hbm2java
 */
public class Students implements java.io.Serializable {

	private String sno;
	private Dormitory dormitory;
	private String sname;
	private String sgender;
	private String spassword;
	private Question question;

	public Students() {
	}

	public Students(String sno, String sname) {
		this.sno = sno;
		this.sname = sname;
	}

	public Students(String sno, Dormitory dormitory, String sname, String sgender, String spassword,
			Question question) {
		this.sno = sno;
		this.dormitory = dormitory;
		this.sname = sname;
		this.sgender = sgender;
		this.spassword = spassword;
		this.question = question;
	}

	public String getSno() {
		return this.sno;
	}

	public void setSno(String sno) {
		this.sno = sno;
	}

	public Dormitory getDormitory() {
		return this.dormitory;
	}

	public void setDormitory(Dormitory dormitory) {
		this.dormitory = dormitory;
	}

	public String getSname() {
		return this.sname;
	}

	public void setSname(String sname) {
		this.sname = sname;
	}

	public String getSgender() {
		return this.sgender;
	}

	public void setSgender(String sgender) {
		this.sgender = sgender;
	}

	public String getSpassword() {
		return this.spassword;
	}

	public void setSpassword(String spassword) {
		this.spassword = spassword;
	}

	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

}
