package hibernate;
// Generated 2016-5-11 22:52:13 by Hibernate Tools 4.3.1.Final

/**
 * Students generated by hbm2java
 */
public class Students implements java.io.Serializable {

	private String sno;
	private String sname;
	private String sgender;
	private Float sgpa;
	private String sroomNr;
	private String spassword;
	private Question question;

	public Students() {
	}

	public Students(String sno, String sname, String sgender) {
		this.sno = sno;
		this.sname = sname;
		this.sgender = sgender;
	}

	public Students(String sno, String sname, String sgender, Float sgpa, String sroomNr, String spassword,
			Question question) {
		this.sno = sno;
		this.sname = sname;
		this.sgender = sgender;
		this.sgpa = sgpa;
		this.sroomNr = sroomNr;
		this.spassword = spassword;
		this.question = question;
	}

	public String getSno() {
		return this.sno;
	}

	public void setSno(String sno) {
		this.sno = sno;
	}

	public String getSname() {
		return this.sname;
	}

	public void setSname(String sname) {
		this.sname = sname;
	}

	public String getSgender() {
		return this.sgender;
	}

	public void setSgender(String sgender) {
		this.sgender = sgender;
	}

	public Float getSgpa() {
		return this.sgpa;
	}

	public void setSgpa(Float sgpa) {
		this.sgpa = sgpa;
	}

	public String getSroomNr() {
		return this.sroomNr;
	}

	public void setSroomNr(String sroomNr) {
		this.sroomNr = sroomNr;
	}

	public String getSpassword() {
		return this.spassword;
	}

	public void setSpassword(String spassword) {
		this.spassword = spassword;
	}

	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

}
